version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/stocktracker

  frontend:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend
